/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantsPlantIdRouteImport } from './routes/plants/$plantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsPlantIdRoute = PlantsPlantIdRouteImport.update({
  id: '/plants/$plantId',
  path: '/plants/$plantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plants/$plantId': typeof PlantsPlantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plants/$plantId': typeof PlantsPlantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plants/$plantId': typeof PlantsPlantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plants/$plantId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plants/$plantId'
  id: '__root__' | '/' | '/plants/$plantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlantsPlantIdRoute: typeof PlantsPlantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$plantId': {
      id: '/plants/$plantId'
      path: '/plants/$plantId'
      fullPath: '/plants/$plantId'
      preLoaderRoute: typeof PlantsPlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlantsPlantIdRoute: PlantsPlantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
